<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(AcademicDepartmentsTableSeeder::class);
        $this->call(EconomyCodesTableSeeder::class);
        $this->call(EconomyHeadsTableSeeder::class);
        $this->call(EmployeesTableSeeder::class);
        $this->call(FeaturesTableSeeder::class);
        $this->call(NotificationTypesTableSeeder::class);
        $this->call(ProjectProposalFilesTableSeeder::class);
        $this->call(ProjectProposalsTableSeeder::class);
        $this->call(ProjectRequestAttachmentsTableSeeder::class);
        $this->call(ProjectRequestForwardTableSeeder::class);
        $this->call(ProjectRequestReceiversTableSeeder::class);
        $this->call(ProjectRequestsTableSeeder::class);
        $this->call(ProjectsTableSeeder::class);
        $this->call(ResearchRequestAttachmentsTableSeeder::class);
        $this->call(ResearchRequestReceiversTableSeeder::class);
        $this->call(ResearchRequestsTableSeeder::class);
        $this->call(RoleUserTableSeeder::class);
        $this->call(WorkflowRuleDetailsTableSeeder::class);
        $this->call(WorkflowRuleMastersTableSeeder::class);
        $this->call(ShareRulesSeeder::class);
        $this->call(DesignationsTableSeeder::class);
        $this->call(ShareRulesDesignationSeeder::class);
        $this->call(DistrictsTableSeeder::class);
        $this->call(DivisionsTableSeeder::class);
        $this->call(ThanasTableSeeder::class);
        $this->call(UnionsTableSeeder::class);
        $this->call(AcademicDegreeTableSeeder::class);
        $this->call(AcademicInstitutesTableSeeder::class);
        $this->call(AccountHeadsTableSeeder::class);
        $this->call(AccountLedgersTableSeeder::class);
        $this->call(AttributePlanningsTableSeeder::class);
        $this->call(AttributeValuesTableSeeder::class);
        $this->call(AttributesTableSeeder::class);
        $this->call(BookingCheckinTableSeeder::class);
        $this->call(BookingGuestInfosTableSeeder::class);
        $this->call(BookingRequestForwardsTableSeeder::class);
        $this->call(BookingRoomInfosTableSeeder::class);
        $this->call(CheckinDetailsTableSeeder::class);
        $this->call(CheckinPaymentsTableSeeder::class);
        $this->call(CheckinRoomTableSeeder::class);
        $this->call(DepartmentsTableSeeder::class);
        $this->call(DraftProposalBudgetFiscalValuesTableSeeder::class);
        $this->call(DraftProposalBudgetsTableSeeder::class);
        $this->call(EmployeeEducationsTableSeeder::class);
        $this->call(EmployeePersonalInfoTableSeeder::class);
        $this->call(EmployeePublicationsTableSeeder::class);
        $this->call(EmployeeResearchInfoTableSeeder::class);
        $this->call(EmployeeTrainingsTableSeeder::class);
        $this->call(FiscalYearsTableSeeder::class);
        $this->call(HostelBudgetSectionsTableSeeder::class);
        $this->call(HostelBudgetTitlesTableSeeder::class);
        $this->call(HostelBudgetsTableSeeder::class);
        $this->call(HostelRoomTypeRatesTableSeeder::class);
        $this->call(HostelsTableSeeder::class);
        $this->call(MonthlyUpdateAttachmentsTableSeeder::class);
        $this->call(MonthlyUpdatesTableSeeder::class);
        $this->call(NotificationsTableSeeder::class);
        $this->call(OrganizablesTableSeeder::class);
        $this->call(OrganizationMembersTableSeeder::class);
        $this->call(OrganizationsTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(PermissionRoleTableSeeder::class);
        $this->call(PermissionsTableSeeder::class);
        $this->call(ProjectDetailProposalAttachmentsTableSeeder::class);
        $this->call(ProjectDetailProposalsTableSeeder::class);
        $this->call(ProjectRequestDetailAttachmentsTableSeeder::class);
        $this->call(ProjectRequestDetailsTableSeeder::class);
        $this->call(ProjectResearchTasksTableSeeder::class);
        $this->call(ProjectTrainingTableSeeder::class);
        $this->call(ProjectTrainingMembersTableSeeder::class);
        $this->call(RegisteredTraineeEducationTableSeeder::class);
        $this->call(RegisteredTraineeEmergencyTableSeeder::class);
        $this->call(RegisteredTraineeGeneralInfosTableSeeder::class);
        $this->call(RegisteredTraineeHealthExamTableSeeder::class);
        $this->call(RegisteredTraineePhysicalInfosTableSeeder::class);
        $this->call(RegisteredTraineeServiceTableSeeder::class);
        $this->call(RemarksTableSeeder::class);
        $this->call(ResearchTableSeeder::class);
        $this->call(ResearchBudgetsTableSeeder::class);
        $this->call(ResearchDetailInvitationAttachmentsTableSeeder::class);
        $this->call(ResearchDetailInvitationsTableSeeder::class);
        $this->call(ResearchDetailSubmissionAttachmentsTableSeeder::class);
        $this->call(ResearchDetailSubmissionsTableSeeder::class);
        $this->call(ResearchProposalDateExtendRequestsTableSeeder::class);
        $this->call(ResearchProposalSubmissionAttachmentsTableSeeder::class);
        $this->call(ResearchProposalSubmissionsTableSeeder::class);
        $this->call(ResearchPublicationAttachmentsTableSeeder::class);
        $this->call(ResearchPublicationsTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(RoomBookingRefereesTableSeeder::class);
        $this->call(RoomBookingRequestersTableSeeder::class);
        $this->call(RoomBookingsTableSeeder::class);
        $this->call(RoomInventoriesTableSeeder::class);
        $this->call(RoomTypesTableSeeder::class);
        $this->call(RoomsTableSeeder::class);
        $this->call(ShareConversationsTableSeeder::class);
        $this->call(ShareRulesTableSeeder::class);
        $this->call(TaskAttachmentsTableSeeder::class);
        $this->call(TaskCommentsTableSeeder::class);
        $this->call(TasksTableSeeder::class);
        $this->call(TraineeDiseasesTableSeeder::class);
        $this->call(TraineesTableSeeder::class);
        $this->call(TrainingsTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(WorkflowConversationsTableSeeder::class);
        $this->call(WorkflowDetailsTableSeeder::class);
        $this->call(WorkflowMastersTableSeeder::class);
    }
}
