<?php

use Illuminate\Database\Seeder;

class ShareRulesDesignationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('share_rules_designations')->delete();
        
        \DB::table('share_rules_designations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 18,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 3,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 19,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 20,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 5,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 17,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 6,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 16,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 7,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'share_rule_id' => 1,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'share_rule_id' => 3,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'share_rule_id' => 3,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 19,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 18,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 3,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'share_rule_id' => 4,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 20,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 5,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'share_rule_id' => 5,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'share_rule_id' => 5,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 19,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 4,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'share_rule_id' => 6,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'share_rule_id' => 6,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 16,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 7,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'share_rule_id' => 7,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 17,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 6,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'share_rule_id' => 7,
                'department_id' => 1,
                'department' => NULL,
                'designation_id' => 22,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 1,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 13,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 8,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 14,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 15,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 10,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 16,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 11,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 17,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 12,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'share_rule_id' => 2,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'share_rule_id' => 8,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'share_rule_id' => 8,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 14,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 13,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 8,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'share_rule_id' => 9,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 15,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 10,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'share_rule_id' => 10,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'share_rule_id' => 10,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 14,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 9,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'share_rule_id' => 11,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'share_rule_id' => 11,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 17,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 12,
                'can_reject' => 1,
                'can_approve' => 1,
                'is_parent' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'share_rule_id' => 12,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 16,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 11,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'share_rule_id' => 12,
                'department_id' => 2,
                'department' => NULL,
                'designation_id' => 23,
                'designation' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'is_sharable' => 1,
                'sharable_id' => 2,
                'can_reject' => 1,
                'can_approve' => 0,
                'is_parent' => 1,
            ),
        ));
        
        
    }
}