<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Faculty Member',
                'email' => 'f@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'FM10',
                'user_type' => 'Employee',
                'mobile' => '01711111111',
                'reference_table_id' => 1,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Faculty Director',
                'email' => 'fd@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'FD11',
                'user_type' => 'Employee',
                'mobile' => '01711111112',
                'reference_table_id' => 2,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Research Director',
                'email' => 'rd@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'RD12',
                'user_type' => 'Employee',
                'mobile' => '01711111113',
                'reference_table_id' => 3,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Project Director',
                'email' => 'pd1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'PD1',
                'user_type' => 'Employee',
                'mobile' => '01711111113',
                'reference_table_id' => 4,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'মহিউদ্দিন জাহাঙ্গীর',
                'email' => 'employee1@bard.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => '10001',
                'user_type' => 'Employee',
                'mobile' => '01254487444',
                'reference_table_id' => 5,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'হামিদুর রহমান',
                'email' => 'employee2@bard.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => '20001',
                'user_type' => 'Employee',
                'mobile' => '01254487445',
                'reference_table_id' => 6,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'মতিউর আমিন',
                'email' => 'employee3@bard.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => '30001',
                'user_type' => 'Employee',
                'mobile' => '01254487446',
                'reference_table_id' => 7,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-02-07 21:28:52',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Director Research',
                'email' => 'dirr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'DIRR',
                'user_type' => 'Employee',
                'mobile' => '01711119113',
                'reference_table_id' => 8,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Asst. Director Research',
                'email' => 'adr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'ADR',
                'user_type' => 'Employee',
                'mobile' => '01711161113',
                'reference_table_id' => 9,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Joint Director Research',
                'email' => 'jdr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'JDR',
                'user_type' => 'Employee',
                'mobile' => '01711111213',
                'reference_table_id' => 10,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Deputy Director Research',
                'email' => 'ddr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'DDR',
                'user_type' => 'Employee',
                'mobile' => '01721111113',
                'reference_table_id' => 11,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Asst. Director General',
                'email' => 'adg@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'ADGR',
                'user_type' => 'Employee',
                'mobile' => '01711211113',
                'reference_table_id' => 13,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Human Resource Faculty',
                'email' => 'hrfm@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'HRM1',
                'user_type' => 'Employee',
                'mobile' => '01711111114',
                'reference_table_id' => 14,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Director Human Resource',
                'email' => 'dirhr@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'DIRHR',
                'user_type' => 'Employee',
                'mobile' => '01723111114',
                'reference_table_id' => 15,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Director Project',
                'email' => 'dirp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'DIRP',
                'user_type' => 'Employee',
                'mobile' => '01711119113',
                'reference_table_id' => 16,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Asst. Director Project',
                'email' => 'adp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'ADP',
                'user_type' => 'Employee',
                'mobile' => '01711161113',
                'reference_table_id' => 17,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Joint Director Project',
                'email' => 'jdp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'JDP',
                'user_type' => 'Employee',
                'mobile' => '01711111213',
                'reference_table_id' => 18,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Deputy Director Project',
                'email' => 'ddp@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hy3h5XfdQK2e3cgke7ebHevS4E7no2Z6149YDVKS5t7WJ7Y9pJyrS',
                'remember_token' => NULL,
                'created_at' => '2019-04-10 13:55:35',
                'updated_at' => '2019-04-10 13:55:35',
                'username' => 'DDP',
                'user_type' => 'Employee',
                'mobile' => '01721111113',
                'reference_table_id' => 19,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
        ));
        
        
    }
}