version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: bard-erp
    ports:
      - 8080:80
    volumes:
      - .:/src/erp
      - ../uploads:/src/uploads
    links:
      - mysql
    environment:
      APP_NAME: BARD ERP
      APP_ENV: development
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8080"
      DB_HOST: mysql
      DB_DATABASE: bard-erp
      DB_USERNAME: bard
      DB_PASSWORD: bs@2345678
      UPLOAD_BASE_PATH: /src/uploads
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: brainstation23.test@gmail.com
      MAIL_PASSWORD: 123456Tt
      MAIL_ENCRYPTION: tls
      MAIL_FROM_NAME: BARD Automation
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bard-erp
      MYSQL_USER: bard
      MYSQL_PASSWORD: bs@2345678
      MYSQL_ROOT_PASSWORD: bs@2345678
    volumes:
      - ./../mysql:/var/lib/mysql
